# Generated by Django 3.0.3 on 2020-03-19 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='relationships',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userRelationships', to='twitter.Relationships'),
        ),
    ]
