# Generated by Django 3.0.3 on 2020-03-13 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='posts',
        ),
    ]
