# Generated by Django 3.0.3 on 2020-03-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0013_auto_20200313_0346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='bodyText',
            field=models.CharField(default='no body text', max_length=200),
        ),
    ]
